server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: http://localhost:3001
          predicates:
            - Path=/user/**
        - id: binarfud
          uri: http://localhost:3000
          predicates:
            - Path=/binarfud/**